

#include <android/log.h>

#define LOGI(TAG, FORMAT, ...) __android_log_print(ANDROID_LOG_INFO, TAG, FORMAT, ##__VA_ARGS__)
#define LOGE(TAG, FORMAT, ...) __android_log_print(ANDROID_LOG_ERROR, TAG, FORMAT, ##__VA_ARGS__)

#define INITIALIZE_SUCCEED 0;
#define INITIALIZE_FAIL 1;

#define VIDEO_STATUS_SUCCESS 0;
#define VIDEO_STATUS_FAILURE -1;
#define VIDEO_ERROR_OPEN 0
#define VIDEO_ERROR_FIND_VIDEO_STREAM_INFO 1
#define VIDEO_ERROR_FIND_VIDEO_STREAM 2
#define VIDEO_ERROR_FIND_DECODER  3
#define VIDEO_ERROR_OPEN_DECODER  4
#define VIDEO_ERROR_CREATE_NATIVE_WINDOW  5
#define VIDEO_ERROR_SET_NATIVE_WINDOW_BUFFER 6
#define VIDEO_ERROR_DECODE_FAIL 7
#define VIDEO_ERROR_RECEIVE_FRAME 8
#define VIDEO_ERROR_CONVERT_DATA 9
#define VIDEO_ERROR_LOCK_NATIVE_WINDOW 10